#theme: jekyll-theme-slate
remote_theme: mmistakes/minimal-mistakes
title: picoG
description: Runs LabVIEW on the Raspberry Pi Pico!
#logo: https://avatars.githubusercontent.com/u/87821763?s=400&v=4

minima:
  # generate social links in footer
  social_links:
    twitter: PicoG42
    github:  picog
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: picog

plugins:
  - jekyll-include-cache
  
