theme: minima
title: PicoG < LabVIEW < PicoG
description: Runs LabVIEW on microcontrollers and more!
logo: https://avatars.githubusercontent.com/u/87821763?s=400&v=4

minima:
  # generate social links in footer
  social_links:
    twitter: picog
    github:  picog
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    linkedin: picog
